# Optional CRD installation for those without Helm hooks
installCRDs: false

## Dex
dex:
  enabled: false

## Redis
redis:
  enabled: true

# This key configures Redis-HA subchart and when enabled (redis-ha.enabled=true)
# the custom redis deployment is omitted
redis-ha:
  enabled: false


## Server
server:
  ingress:
    enabled: false

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  config:
    repositories: |
      - url: ${git_repository}
        passwordSecret:
          name: argocd
          key: password
        usernameSecret:
          name: argocd
          key: username

  additionalApplications:
  - name: bootstrap
    project: default
    namespace: ${namespace}
    source:
      repoURL: ${git_repository}
      targetRevision: HEAD
      path: ${git_path}
      helm:
        values: |-
          cluster: ${cluster_name}
          spec:
            destination:
              server: https://kubernetes.default.svc
            source:
              repoURL: ${git_repository}
              targetRevision: HEAD
              path: ${git_path}
    destination:
      server: https://kubernetes.default.svc
      namespace: ${namespace}            
    syncPolicy:
      automated:
        prune: true
      syncOptions:
        - CreateNamespace=true

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - wget -qO- https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz | tar -xvzf - &&
        mv linux-amd64/helm /custom-tools/helm &&
        chmod 777 /custom-tools/helm
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/helm
    name: custom-tools
    subPath: helm