installCRDs: false

dex:
  enabled: false

server:

  ingress: 
    enabled: true
    annotations: 
      # This annotations adds should be replaced with "ssl-passthrough" to allow both gRPC/HTTPS.
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      # This annotations allows both gRPC/HTTPS on the same ingress but requires 
      # "--enable-ssl-passthrough" to be added to the running nginx ingress controller.
      # nginx.ingress.kubernetes.io/ssl-passthrough: true
    hosts:
      - argo.${cluster_name}.k8s.littleglitch.com
    paths:
      - /
    tls:
      - hosts:
        - argo.${cluster_name}.k8s.littleglitch.com

  config:
    url: argo.${cluster_name}.k8s.littleglitch.com
    repositories: |
      - url: ${git_repository}
        passwordSecret:
          name: argocd
          key: password
        usernameSecret:
          name: argocd
          key: username
  additionalApplications:
  - name: bootstrap
    namespace: ${namespace}
    project: default
    source:
      repoURL: ${git_repository}
      targetRevision: ${git_branch}
      path: ${cluster_name}
      helm:
        values: |-
          cluster: ${cluster_name}
          environment: ${environment}
          spec:
            destination:
              server: https://kubernetes.default.svc
            source:
              repoURL: ${git_repository}
              targetRevision: ${git_branch} 
    destination:
      server: https://kubernetes.default.svc
      namespace: ${namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: false

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - apk add curl &&
        wget -qO- https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar -xvzf - &&
        mv linux-amd64/helm /custom-tools/helm-v3 &&
        wget -qO- https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz | tar -xvzf - &&
        mv linux-amd64/helm /custom-tools/helm-v2 &&
        curl https://gist.githubusercontent.com/cldmnky/da87b8d555c951251b503c668dab2248/raw/6e6f8e302ff1116300877f294f08f97b9cf495ac/helm-wrapper.sh > /custom-tools/helm &&
        chmod 777 /custom-tools/helm
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/helm-v2
    name: custom-tools
    subPath: helm-v2
  - mountPath: /usr/local/bin/helm-v3
    name: custom-tools
    subPath: helm-v3
  - mountPath: /usr/local/bin/helm
    name: custom-tools
    subPath: helm